name: PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: "20"

      - run: npm ci

      - run: npm test --passWithNoTest
      - run: npm run build
